### ISSUE TITLE
使用v-if 渲染的时候会报destroy undefined的错误

### ISSUE THREAD

**Issue by zhzpeng** [huangjincq/vue-better-scroll#1]
![image](https://user-images.githubusercontent.com/13147702/33307892-37ffde6a-d453-11e7-9670-3c4b3f671416.png)
在destroy的时候需要添加非空判断

**Comment by huangjincq** [comment]
问题已经修复，感谢指出

**Comment by zhzpeng** [comment]
![image](https://user-images.githubusercontent.com/13147702/33552743-081fa38c-d931-11e7-9178-1cf01173b51c.png)
这里也要加一下非空判断

**Comment by huangjincq** [comment]
很抱歉，已修复
