### ISSUE TITLE
在有蒙层的情况下列表页还可以上下滑动

### ISSUE THREAD

**Issue by zhangyongqiang010** [huangjincq/vue-better-scroll#23]
经过查看，页面在上下滚动时候，`js` 对 `div.wrapper` 添加了 ` transform：translate(0px)` 的样式, 如果去除就不会出现这样的问题了！这样的话 npm 引入就不行了！

**Comment by huangjincq** [comment]
打开model的层的时候 调用 this.$refs.scroll.disable() 方法
关闭model层的时候 调用 this.$refs.scroll.enable() 方法
