### ISSUE TITLE
异步加载数据时的显示问题

### ISSUE THREAD

**Issue by momoxiaoqing** [huangjincq/vue-better-scroll#4]
列表数据异步获取时，“加载更多”和刷新图标会先加载，然后才加载数据，如图：
![vue-better-scroll](https://user-images.githubusercontent.com/10261128/36968093-7debf306-209c-11e8-921e-1ad41dfc4c2e.png)

目前本人很简单粗暴的解决方法是：
` .wrapper .list-content{
    min-height: 100vh;
  }` 

这个问题初始化的时候应该是可以解决的，然而很忧伤的没能看懂源码，也找不到initScroll使用方法或者例子，求解决方法||想法。
本人，目前也是采用这种方案，后期可能进行改进

**Comment by suyanhanx** [comment]
可以参考一下cube-ui里scroll组件对better-scroll的封装？
