### ISSUE TITLE
用鼠标中键滚动时，滚动到最后一条不会触发加载更多。

### ISSUE THREAD

**Issue by ijustyce** [huangjincq/vue-better-scroll#5]
如题，已经添加了    :listenScroll="listenScroll"    但不懂如何判断是否已经是最后一条。

**Comment by huangjincq** [comment]
1.移动端组件，哪来的鼠标滚轮滚动
2.是否滚动到最后一条，是根据后端给你返回的数据进行判断，加上 listenScroll 属性 或者 :listenScroll="true" 可开启滚动监听 才能在滚动时派发 scroll 事件
3.请仔细阅读文档示例，已经b-scroll 原文档
