### ISSUE TITLE
解决 滚动内容小于滚动区域时有机率无法滚动

### ISSUE THREAD

**Issue by shimangdian** [huangjincq/vue-better-scroll#68]
请大佬@huangjincq      合并 这个pr   https://github.com/huangjincq/vue-better-scroll/pull/66#issue-995828956  ，我测试了有用

**Comment by huangjincq** [comment]
正常来说 mounted 的时候是可以获取到 dom元素的高度，不应该放到 this.$nextTick 中调用。
是不是你的父元素首先不显示等等原因，获取不到宽度，应当考虑元素显示的时候重新 mounted 重新挂载一次，而不是放到 this.$nextTick 中去获取宽度
